# Generated by Django 3.1.1 on 2020-09-12 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newscontent.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=newscontent.services.section_image_directory)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 12, 14, 17, 51, 141043))),
                ('like', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=newscontent.services.new_image_directory)),
                ('picture2', models.ImageField(blank=True, null=True, upload_to=newscontent.services.new_image_directory)),
                ('picture3', models.ImageField(blank=True, null=True, upload_to=newscontent.services.new_image_directory)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newscontent.section')),
            ],
        ),
    ]
