# Generated by Django 3.1.1 on 2020-09-12 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='old_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 15, 48, 17, 387804)),
        ),
    ]
