# Generated by Django 3.1.1 on 2020-09-16 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0003_auto_20200916_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='value',
            new_name='valute',
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 17, 37, 44, 499275)),
        ),
    ]
