# Generated by Django 3.1.1 on 2020-09-16 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0004_auto_20200916_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 19, 29, 54, 750144)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='valute',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
