# Generated by Django 3.1.1 on 2020-09-19 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0010_auto_20200917_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 11, 2, 40, 550869)),
        ),
    ]
