# Generated by Django 3.1.1 on 2020-09-30 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0014_auto_20200929_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 15, 55, 26, 189560)),
        ),
    ]
