# Generated by Django 3.1.1 on 2020-10-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0015_auto_20200930_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 10, 29, 1, 753309)),
        ),
    ]
