# Generated by Django 3.1 on 2020-08-09 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 9, 14, 6, 19, 347038))),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
