# Generated by Django 3.1 on 2020-08-17 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0003_auto_20200809_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 18, 34, 0, 56426)),
        ),
    ]
