# Generated by Django 3.1 on 2020-08-18 12:17

import datetime
from django.db import migrations, models
import newscontent.models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0004_auto_20200817_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=newscontent.models.new_directory_path),
        ),
        migrations.AddField(
            model_name='new',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 16, 17, 25, 651943)),
        ),
    ]
