# Generated by Django 3.1.1 on 2020-09-12 13:29

import datetime
from django.conf import settings
from django.db import migrations, models
import newscontent.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newscontent', '0005_auto_20200818_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=newscontent.models.new_directory_section),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 13, 29, 3, 802195)),
        ),
    ]
